replicaCount: 1
image: <+artifact.image>
# image:
# repository: nginx
# tag: stable
# pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
